export declare const CLIPBOARD_FORMAT = "text/json";
export declare const DELIMITERS: string[];
export declare const UNDO_BUFFER_CAPACITY = 100;
export declare const DEFAULT_KEYBOARD_DROPDOWN_DISPLAY_TIME = 1500;
export declare const DEFAULT_SORT_OPTION_WIDTH = 200;
export declare const DEFAULT_SORT_PILL_WIDTH = 90;
export declare const DEFAULT_DATE_FORMAT = "YYYY-MM-DD";
export declare const DEFAULT_DATE_TIME_FORMAT = "YYYY-MM-DD HH:mm:ss";
export declare const COMPACT_HEIGHT = 24;
export declare const NORMAL_HEIGHT = 30;
export declare const LARGE_HEIGHT = 36;
export declare const COMPACT_PILL_HEIGHT = 18;
export declare const NORMAL_PILL_HEIGHT = 22;
export declare const LARGE_PILL_HEIGHT = 26;
export declare const AND = "and";
export declare const OR = "or";
export declare const EQUALS = "=";
export declare const EMPTY = "Empty";
export declare const defaultComparisons: string[];
export declare const stringComparisons: string[];
export declare const numberComparisons: string[];
export declare const DEFAULT_PAGE_SIZE = 10;
export declare const KeyBoardkeys: {
    ArrowRight: string;
    ArrowLeft: string;
    ArrowUp: string;
    ArrowDown: string;
    PageUp: string;
    PageDown: string;
    Home: string;
    End: string;
    Enter: string;
    Tab: string;
    c: string;
    C: string;
    x: string;
    X: string;
    v: string;
    V: string;
};
export declare const AgTypes: {
    text: string;
    boolean: string;
    number: string;
    date: string;
    dateString: string;
};
export declare const AgFilters: {
    agSetColumnFilter: string;
    agTextColumnFilter: string;
    agNumberColumnFilter: string;
    agBooleanColumnFilter: string;
    agDateColumnFilter: string;
    agDateStringColumnFilter: string;
};
export declare const VALUE = "value";
export declare const VALUE_TO = "valueTo";
export declare const VALUE_ARRAY = "valueArray";
